apiVersion: v1
kind: Secret
metadata:
  name: goapp-secret
type: Opaque
stringData:  # no need to worry about converting to base64
  API_NAME: "go-app"
  API_HOST: "0.0.0.0"
  API_PORT: "3000"
  API_REQUEST_LOG: "true"
  API_RUN_SWAGGER: "false"
  API_AUTH_TYPE: "jwt"
  API_RPCPORT: "50051"

  CORS_ALLOWED_ORIGINS: "http://0.0.0.0:3000"

  DB_MAX_CONNECTION_POOL: "4" # number of connections :  ((core_count * 2) + effective_spindle_count)
  DB_MAX_IDLE_CONNECTIONS: "4"
  DB_CONNECTIONS_MAX_LIFETIME: "300s"

  REDIS_NAME: "0"
  REDIS_CACHE_TIME: "5s"
  REDIS_ENABLE: "true"

  SESSION_SESSION_NAME: "session"
  SESSION_PATH: "/"
  SESSION_DURATION: "1440m"
  SESSION_HTTP_ONLY: "false"
  SESSION_SECURE: "false"

  JWT_SECRET: "hey-you"

  ADMIN_PASSWORD: "gyMs4cN0Gmbre9Uj"
