apiVersion: v1
kind: Service
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
    - name: grpc
      port: 8181
      targetPort: 50051
