apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  labels:
    app: pg-db
spec:
  selector:
    matchLabels:
      app: pg-db
      tier: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-db
        tier: postgres
    spec:
      containers:
        - image: postgres:16.0
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: pgdb-secret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim



