apiVersion: v1
kind: Service
metadata:
  name: pg-db
  labels:
    app: pg-db
spec:
  type: NodePort #Only debug for test project if you go prod change it to cluster ip
  ports:
    - port: 5432
  selector:
    app: pg-db
    tier: postgres