apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource
metadata:
  name: pg-db                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: pg-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=pg-db,tier=postgres`
    app: pg-db
    tier: postgres