// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: proto/v1/rate_limit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RateLimit_CheckRateLimit_FullMethodName = "/rate_limit.RateLimit/CheckRateLimit"
)

// RateLimitClient is the client API for RateLimit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimitClient interface {
	CheckRateLimit(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type rateLimitClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimitClient(cc grpc.ClientConnInterface) RateLimitClient {
	return &rateLimitClient{cc}
}

func (c *rateLimitClient) CheckRateLimit(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, RateLimit_CheckRateLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitServer is the server API for RateLimit service.
// All implementations must embed UnimplementedRateLimitServer
// for forward compatibility
type RateLimitServer interface {
	CheckRateLimit(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedRateLimitServer()
}

// UnimplementedRateLimitServer must be embedded to have forward compatible implementations.
type UnimplementedRateLimitServer struct {
}

func (UnimplementedRateLimitServer) CheckRateLimit(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRateLimit not implemented")
}
func (UnimplementedRateLimitServer) mustEmbedUnimplementedRateLimitServer() {}

// UnsafeRateLimitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimitServer will
// result in compilation errors.
type UnsafeRateLimitServer interface {
	mustEmbedUnimplementedRateLimitServer()
}

func RegisterRateLimitServer(s grpc.ServiceRegistrar, srv RateLimitServer) {
	s.RegisterService(&RateLimit_ServiceDesc, srv)
}

func _RateLimit_CheckRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServer).CheckRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimit_CheckRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServer).CheckRateLimit(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimit_ServiceDesc is the grpc.ServiceDesc for RateLimit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rate_limit.RateLimit",
	HandlerType: (*RateLimitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRateLimit",
			Handler:    _RateLimit_CheckRateLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/rate_limit.proto",
}
